[package]
version.workspace = true
license.workspace = true
edition.workspace = true

name = "db-proto"
# readme = "../../README.md"
description = ""

[lib]
name = "db_proto"
path = "lib.rs"

[dependencies]
parking_lot = { workspace = true }
