[env]
bin = "target"
entry = "entry.rs"
flags = "-O -C codegen-units=1"

[project]
name = "playground"

[tasks.clean]
script = ["rm -rf %{arg.1}/target", "mkdir %{arg.1}/target"]

[tasks.run]
script = ["maid build -q %{arg.1}", "./%{arg.1}/%{env.bin}/bin"]

[tasks.build]
depends = ["clean"]
script = ["rustc %{arg.1}/%{env.entry} %{env.flags} -o %{arg.1}/%{env.bin}/bin"]
