[package]
version.workspace = true
license.workspace = true
edition.workspace = true

name = "fast"
# readme = "../../README.md"
description = "the FAST database"

[[bin]]
name = "fast-cli"
path = "client.rs"

[[bin]]
name = "fast-server"
path = "server.rs"

[dependencies]
rustyline = "15.0.0"
clap.workspace = true
bytes.workspace = true
tokio.workspace = true
tracing.workspace = true
fast-proto.workspace = true
fast-server.workspace = true
parking_lot.workspace = true
tracing-subscriber.workspace = true
