[package]
name = "http"
version = "0.1.0"
edition = "2021"

[dependencies]
server = { path = "crates/server" }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
