[project]
name = "blaze"
version = "0.1.6"

[tasks]
serve.script = "fleet run --release"
publish.script = [
	"cargo publish --package blaze --no-verify", 
	"cargo publish --package blaze-macros --no-verify"
]