[package]
version.workspace = true
license.workspace = true
edition.workspace = true

name = "kade-proto"
description = "Protocol internals for kade"

[lib]
name = "kade_proto"
path = "lib.rs"

[dependencies]
atoi.workspace = true
bytes.workspace = true
tokio.workspace = true
serde.workspace = true
bincode.workspace = true
tracing.workspace = true
async-stream.workspace = true
tokio-stream.workspace = true
