[package]
name = "meow"
version = "0.0.1"
edition = "2021"

[dependencies]
cfg-if = "1.0.0"
clap = { version = "4.5.17", features = ["derive"] }
crossterm = "0.27.0"
ropey = "1.6.1"
unicode-segmentation = "1.11.0"
unicode-width = "0.1.13"

# local syntaxes
tree-sitter-html = { path = "crates/tree-sitter-html" }
tree-sitter-asm = { path = "crates/tree-sitter-asm" }
tree-sitter-scss = { path = "crates/tree-sitter-scss" }
tree-sitter-docker = { path = "crates/tree-sitter-docker" }

# tree sitter
tree-sitter = "0.23.0"
tree-sitter-highlight = "0.23.0"
tree-sitter-rust = "0.23.0"
tree-sitter-md = "0.3.2"
tree-sitter-toml-ng = "0.6.0"
tree-sitter-javascript = "0.23.0"
tree-sitter-json = "0.23.0"
tree-sitter-typescript = "0.23.0"
tree-sitter-python = "0.23.2"
tree-sitter-go = "0.23.1"
tree-sitter-bash = "0.23.1"
tree-sitter-yaml = "0.6.1"
tree-sitter-r = "1.1.0"
tree-sitter-c = "0.23.0"
tree-sitter-css = "0.23.0"
tree-sitter-lua = "0.2.0"

[build-dependencies]
cc = "*"

[target.'cfg(any(target_os = "windows", target_os = "macos", target_os = "linux", target_os = "freebsd", target_os = "dragonfly", target_os = "openbsd", target_os = "netbsd"))'.dependencies]
arboard = { version = "3.4.1", features = ["wayland-data-control"] }
