[[languages]]
name = "ada"
repo = "https://github.com/briot/tree-sitter-ada"

[[languages]]
name = "asm"
repo = "https://github.com/rush-rs/tree-sitter-asm"

[[languages]]
name = "awk"
repo = "https://github.com/Beaglefoot/tree-sitter-awk"

[[languages]]
name = "bash"
repo = "https://github.com/tree-sitter/tree-sitter-bash"

[[languages]]
name = "bibtex"
repo = "https://github.com/latex-lsp/tree-sitter-bibtex"

[[languages]]
name = "bicep"
repo = "https://github.com/amaanq/tree-sitter-bicep"

[[languages]]
name = "blueprint"
repo = "https://gitlab.com/gabmus/tree-sitter-blueprint"

[[languages]]
name = "c"
repo = "https://github.com/tree-sitter/tree-sitter-c"

[[languages]]
name = "capnp"
repo = "https://github.com/amaanq/tree-sitter-capnp"

[[languages]]
name = "clojure"
repo = "https://github.com/sogaiu/tree-sitter-clojure"

[[languages]]
name = "c_sharp"
repo = "https://github.com/tree-sitter/tree-sitter-c-sharp"

[[languages]]
name = "cpp"
repo = "https://github.com/tree-sitter/tree-sitter-cpp"

[[languages]]
name = "css"
repo = "https://github.com/tree-sitter/tree-sitter-css"

[[languages]]
name = "cue"
repo = "https://github.com/eonpatapon/tree-sitter-cue"

[[languages]]
name = "d"
repo = "https://github.com/gdamore/tree-sitter-d"

[[languages]]
name = "dart"
repo = "https://github.com/UserNobody14/tree-sitter-dart"

[[languages]]
name = "diff"
repo = "https://github.com/the-mikedavis/tree-sitter-diff"

[[languages]]
name = "dockerfile"
repo = "https://github.com/camdencheek/tree-sitter-dockerfile"

[[languages]]
name = "eex"
repo = "https://github.com/connorlay/tree-sitter-eex"

[[languages]]
name = "elisp"
repo = "https://github.com/Wilfred/tree-sitter-elisp"

[[languages]]
name = "elixir"
repo = "https://github.com/elixir-lang/tree-sitter-elixir"

[[languages]]
name = "elm"
repo = "https://github.com/elm-tooling/tree-sitter-elm"

[[languages]]
name = "erlang"
repo = "https://github.com/WhatsApp/tree-sitter-erlang"

[[languages]]
name = "forth"
repo = "https://github.com/AlexanderBrevig/tree-sitter-forth"

[[languages]]
name = "fortran"
repo = "https://github.com/stadelmanma/tree-sitter-fortran"

[[languages]]
name = "fish"
repo = "https://github.com/ram02z/tree-sitter-fish"

[[languages]]
name = "gdscript"
repo = "https://github.com/PrestonKnopp/tree-sitter-gdscript"

[[languages]]
name = "gleam"
repo = "https://github.com/gleam-lang/tree-sitter-gleam"

[[languages]]
name = "glsl"
repo = "https://github.com/theHamsta/tree-sitter-glsl"

[[languages]]
name = "go"
repo = "https://github.com/tree-sitter/tree-sitter-go"

[[languages]]
name = "haskell"
repo = "https://github.com/tree-sitter/tree-sitter-haskell"

[[languages]]
name = "hcl"
repo = "https://github.com/MichaHoffmann/tree-sitter-hcl"

[[languages]]
name = "heex"
repo = "https://github.com/phoenixframework/tree-sitter-heex"

[[languages]]
name = "html"
repo = "https://github.com/tree-sitter/tree-sitter-html"

[[languages]]
name = "ini"
repo = "https://github.com/justinmk/tree-sitter-ini"

[[languages]]
name = "java"
repo = "https://github.com/tree-sitter/tree-sitter-java"

[[languages]]
name = "javascript"
repo = "https://github.com/tree-sitter/tree-sitter-javascript"

[[languages]]
name = "json"
repo = "https://github.com/tree-sitter/tree-sitter-json"

[[languages]]
name = "jsx"
repo = "https://github.com/tree-sitter/tree-sitter-javascript"

[[languages]]
name = "julia"
repo = "https://github.com/tree-sitter/tree-sitter-julia"

[[languages]]
name = "kotlin"
repo = "https://github.com/fwcd/tree-sitter-kotlin"

[[languages]]
name = "latex"
repo = "https://github.com/latex-lsp/tree-sitter-latex"

[[languages]]
name = "llvm"
repo = "https://github.com/benwilliamgraham/tree-sitter-llvm"

[[languages]]
name = "lua"
repo = "https://github.com/tjdevries/tree-sitter-lua"

[[languages]]
name = "make"
repo = "https://github.com/alemuller/tree-sitter-make"

[[languages]]
name = "markdown"
repo = "https://github.com/tree-sitter-grammars/tree-sitter-markdown"

[[languages]]
name = "matlab"
repo = "https://github.com/acristoffers/tree-sitter-matlab"

[[languages]]
name = "meson"
repo = "https://github.com/Decodetalkers/tree-sitter-meson"

[[languages]]
name = "nix"
repo = "https://github.com/nix-community/tree-sitter-nix"

[[languages]]
name = "objc"
repo = "https://github.com/tree-sitter-grammars/tree-sitter-objc"

[[languages]]
name = "ocaml"
repo = "https://github.com/tree-sitter/tree-sitter-ocaml"

[[languages]]
name = "ocaml_interface"
repo = "https://github.com/tree-sitter/tree-sitter-ocaml"

[[languages]]
name = "openscad"
repo = "https://github.com/bollian/tree-sitter-openscad"

[[languages]]
name = "pascal"
repo = "https://github.com/Isopod/tree-sitter-pascal"

[[languages]]
name = "php"
repo = "https://github.com/tree-sitter/tree-sitter-php"

[[languages]]
name = "plaintext"
repo = "https://github.com/the-mikedavis/tree-sitter-diff"

[[languages]]
name = "proto"
repo = "https://github.com/treywood/tree-sitter-proto"

[[languages]]
name = "python"
repo = "https://github.com/tree-sitter/tree-sitter-python"

[[languages]]
name = "r"
repo = "https://github.com/r-lib/tree-sitter-r/"

[[languages]]
name = "racket"
repo = "https://github.com/6cdh/tree-sitter-racket"

[[languages]]
name = "regex"
repo = "https://github.com/tree-sitter/tree-sitter-regex"

[[languages]]
name = "ruby"
repo = "https://github.com/tree-sitter/tree-sitter-ruby"

[[languages]]
name = "rust"
repo = "https://github.com/tree-sitter/tree-sitter-rust"

[[languages]]
name = "scala"
repo = "https://github.com/tree-sitter/tree-sitter-scala"

[[languages]]
name = "scheme"
repo = "https://github.com/6cdh/tree-sitter-scheme"

[[languages]]
name = "scss"
repo = "https://github.com/serenadeai/tree-sitter-scss"

[[languages]]
name = "sql"
repo = "https://github.com/DerekStride/tree-sitter-sql"

[[languages]]
name = "svelte"
repo = "https://github.com/Himujjal/tree-sitter-svelte"

[[languages]]
name = "swift"
repo = "https://github.com/alex-pinkus/tree-sitter-swift"

[[languages]]
name = "toml"
repo = "https://github.com/tree-sitter/tree-sitter-toml"

[[languages]]
name = "typescript"
repo = "https://github.com/tree-sitter/tree-sitter-typescript"

[[languages]]
name = "tsx"
repo = "https://github.com/tree-sitter/tree-sitter-typescript"

[[languages]]
name = "vim"
repo = "https://github.com/neovim/tree-sitter-vim"

[[languages]]
name = "wast"
repo = "https://github.com/wasm-lsp/tree-sitter-wasm"

[[languages]]
name = "wat"
repo = "https://github.com/wasm-lsp/tree-sitter-wasm"

[[languages]]
name = "x86asm"
repo = "https://github.com/bearcove/tree-sitter-x86asm"

[[languages]]
name = "wgsl"
repo = "https://github.com/szebniok/tree-sitter-wgsl"

[[languages]]
name = "yaml"
repo = "https://github.com/ikatyang/tree-sitter-yaml"

[[languages]]
name = "zig"
repo = "https://github.com/maxxnino/tree-sitter-zig"