[project]
name = "meow-editor"
version = "1.0.0"

[tasks]
test.script = ["fleet run --release samples/sample.%{arg.1}"]
install.script = "cargo install --path ."
compress.script = "tar cJf languages.tar.xz languages/*"