[project]
name = "fast"
version = "0.0.1"

[tasks]
cli.script = "fleet run -q --release --bin fast-cli %{arg.1} %{arg.2} %{arg.3}"
server.script = "fleet run --release --bin fast-server -- --state db-state.bin"