[package]
version.workspace = true
license.workspace = true
edition.workspace = true

name = "db-server"
# readme = "../../README.md"
description = ""

[lib]
name = "db_server"
path = "server.rs"

[dependencies]
tokio.workspace = true
tracing.workspace = true
db-proto.workspace = true
