[package]
version.workspace = true
license.workspace = true
edition.workspace = true

name = "fast-server"
readme = "../../README.md"
description = "Server internals for FAST"

[lib]
name = "fast_server"
path = "server.rs"

[dependencies]
tokio.workspace = true
tracing.workspace = true
fast-proto.workspace = true
