[package]
name = "codegen"
version = "0.0.1"
edition = "2021"

[lib]
name = "codegen"
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
