[package]
name = "server"
version = "0.0.1"
edition = "2021"

[lib]
name = "server"
path = "lib.rs"

[dependencies]
serde_json = "1.0.128"
codegen = { path = "../codegen" }
serde = { version = "1.0.210", features = ["derive"] }
tokio = { version = "1.40.0", features = ["full"] }
